"""Tests for render staleness visibility (#431: stale context.md produces no
warning when the scheduled render job silently calls the wrong binary).

Two mechanisms:
  * cmd_render prints a versioned, timestamped audit line after writing --output.
  * perseus doctor flags rendered outputs older than render.staleness_warn_hours.
"""
import argparse
import copy
import os
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest

from conftest import PY_VER, cfg, perseus

pytestmark = pytest.mark.skipif(PY_VER < (3, 10), reason="Perseus requires Python 3.10+")


# ── audit line on render-to-file ──────────────────────────────────────────────

def test_render_to_file_prints_audit_line(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr(perseus, "PERSEUS_HOME", tmp_path / "home")
    (tmp_path / "home").mkdir()
    src = tmp_path / "ctx.md"
    src.write_text("# Hello\n", encoding="utf-8")
    out = tmp_path / "AGENTS.md"  # fresh path (does not exist yet)
    perseus.cmd_render(argparse.Namespace(command="render", source=str(src), output=str(out)), {})
    line = capsys.readouterr().out
    assert f"perseus {perseus._PERSEUS_VERSION}" in line
    assert "rendered" in line
    assert "bytes" in line
    assert str(out) in line


def test_render_quiet_suppresses_audit_line(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr(perseus, "PERSEUS_HOME", tmp_path / "home")
    (tmp_path / "home").mkdir()
    src = tmp_path / "ctx.md"
    src.write_text("# Hello\n", encoding="utf-8")
    out = tmp_path / "AGENTS.md"
    perseus.cmd_render(
        argparse.Namespace(command="render", source=str(src), output=str(out), quiet=True), {})
    assert capsys.readouterr().out == ""


def test_render_to_stdout_has_no_audit_line(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr(perseus, "PERSEUS_HOME", tmp_path / "home")
    (tmp_path / "home").mkdir()
    src = tmp_path / "ctx.md"
    src.write_text("# Hello\n", encoding="utf-8")
    perseus.cmd_render(argparse.Namespace(command="render", source=str(src), output=None), {})
    out = capsys.readouterr().out
    assert "rendered" not in out  # no audit line mixed into the document
    assert "# Hello" in out


def test_render_failure_prints_structured_marker(tmp_path, monkeypatch, capsys):
    # #799: a failed run must leave a stamped, greppable marker on stderr so a
    # noisy render-agent log makes the current run's outcome obvious.
    monkeypatch.setattr(perseus, "PERSEUS_HOME", tmp_path / "home")
    (tmp_path / "home").mkdir()
    missing = tmp_path / "does_not_exist.md"
    with pytest.raises(SystemExit):
        perseus.cmd_render(
            argparse.Namespace(command="render", source=str(missing), output=None), {})
    err = capsys.readouterr().err
    assert f"perseus {perseus._PERSEUS_VERSION}" in err
    assert "render FAILED" in err
    assert "source not found" in err
    assert str(missing) in err


# ── doctor freshness check ────────────────────────────────────────────────────

def _gen_header(when_utc: datetime) -> str:
    stamp = when_utc.strftime("%Y-%m-%d %H:%M")
    return f"> This file is generated by [Perseus](x) v1.0.9 on {stamp} UTC.\n# body\n"


def test_doctor_freshness_ok_when_recent(tmp_path):
    (tmp_path / "AGENTS.md").write_text(
        _gen_header(datetime.now(timezone.utc)), encoding="utf-8")
    r = perseus._doctor_check_render_freshness(cfg(), tmp_path)
    assert r.status == "ok"
    assert r.id == "render_freshness"


def test_doctor_freshness_warns_on_stale_header(tmp_path):
    (tmp_path / "AGENTS.md").write_text(
        _gen_header(datetime.now(timezone.utc) - timedelta(days=10)), encoding="utf-8")
    r = perseus._doctor_check_render_freshness(cfg(), tmp_path)
    assert r.status == "warn"
    assert "AGENTS.md" in r.value
    assert r.remediation


def test_doctor_freshness_uses_mtime_when_no_header(tmp_path):
    p = tmp_path / "AGENTS.md"
    p.write_text("# plain rendered output, no perseus header\n", encoding="utf-8")
    old = time.time() - 10 * 86400
    os.utime(p, (old, old))
    r = perseus._doctor_check_render_freshness(cfg(), tmp_path)
    assert r.status == "warn"


def test_doctor_freshness_disabled(tmp_path):
    (tmp_path / "AGENTS.md").write_text(
        _gen_header(datetime.now(timezone.utc) - timedelta(days=10)), encoding="utf-8")
    c = copy.deepcopy(perseus.DEFAULT_CONFIG)
    c["render"]["staleness_warn_hours"] = 0
    r = perseus._doctor_check_render_freshness(c, tmp_path)
    assert r.status == "ok"
    assert "disabled" in r.value


def test_doctor_freshness_no_outputs(tmp_path):
    r = perseus._doctor_check_render_freshness(cfg(), tmp_path)
    assert r.status == "ok"
    assert "no rendered outputs" in r.value


def test_doctor_freshness_names_exact_path(tmp_path):
    # #798: the warning must name the exact file, not a bare "AGENTS.md", so a
    # multi-AGENTS setup doesn't send the operator to audit the wrong one.
    ws = tmp_path / "sam"
    ws.mkdir()
    (ws / "AGENTS.md").write_text(
        _gen_header(datetime.now(timezone.utc) - timedelta(days=10)), encoding="utf-8")
    r = perseus._doctor_check_render_freshness(cfg(), ws)
    assert r.status == "warn"
    # The distinctive parent dir is present in both summary and remediation,
    # i.e. the full path is shown rather than the ambiguous basename alone.
    assert "sam" in r.value
    assert "sam" in r.remediation
    # Remediation points operators at the two things that actually resolve it.
    assert "staleness_watch" in r.remediation
    assert "startup-memory route" in r.remediation


def test_doctor_freshness_flags_watched_out_of_workspace_target(tmp_path):
    # A fresh workspace AGENTS.md but a stale startup target rendered OUTSIDE the
    # workspace (the #798 shape): a staleness_watch entry points at the real
    # target, and the warning names that exact out-of-workspace path.
    ws = tmp_path / "sam"
    ws.mkdir()
    (ws / "AGENTS.md").write_text(
        _gen_header(datetime.now(timezone.utc)), encoding="utf-8")  # fresh
    target = tmp_path / "rovo" / "AGENTS.md"
    target.parent.mkdir()
    target.write_text(
        _gen_header(datetime.now(timezone.utc) - timedelta(days=10)), encoding="utf-8")
    c = cfg()
    c["render"]["staleness_watch"] = [str(target)]
    r = perseus._doctor_check_render_freshness(c, ws)
    assert r.status == "warn"
    assert "rovo" in r.remediation  # the stale out-of-workspace target is named


def test_doctor_freshness_registered():
    assert perseus._doctor_check_render_freshness in perseus._DOCTOR_CHECKS
